feat: CLIN-2343 re-add prescription table
Ferlab-Ste-Justine/clin-prescription-ui pull request #49
Opened 2023-11-08 22:53 UTC by oliviercperrier

# FEAT

- closes #2343

## Description

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2343)

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI/Screenshot Approved from design

## Screenshot

### After
<img width="1512" alt="Screenshot 2023-11-08 at 5 53 31 PM" src="https://github.com/Ferlab-Ste-Justine/clin-prescription-ui/assets/28421005/bd687570-c66c-4f01-a6c8-a7b0991964b3">

## QA

Steps to validate
Url (storybook, ...)
...

## Mention

2023-11-14 16:01 UTC, ethienneroy requested changes

2023-11-14 16:01 UTC, ethienneroy commented on src/views/Home/index.tsx
> +            title={<Title level={3}>Mes Prescriptions</Title>}
fichiers traduction?

2023-11-14 17:40 UTC, oliviercperrier commented on src/views/Home/index.tsx
> +            title={<Title level={3}>Mes Prescriptions</Title>}
C'était comme ca mais je peux les mettre dans le fichier

2023-11-14 17:41 UTC, oliviercperrier commented on src/views/Home/index.tsx
> +                      description="Trouver une analyse en cours et rajouter un membre de la famille"
meme chose

2023-11-16 12:54 UTC, AltefrohneGaelle approved these changes

2023-11-16 13:49 UTC, merged