feat: CLIN-2357 ajout colonne code du ministere
Ferlab-Ste-Justine/clin-prescription-ui pull request #60
Opened 2023-12-13 20:51 UTC by claudia1296

# FEAT:  Ajouter colonne ‘Code du ministère’ 

- closes #CLIN-2357

## Description
Ajouter colonne ‘Code du ministère’ mettre en 2eme position du tableau

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2357)

## Screenshot
### Before

### After
![image](https://github.com/Ferlab-Ste-Justine/clin-prescription-ui/assets/52966302/cd4b7130-2aa5-45bd-810f-0715fc2c4835)

## QA

Steps to validate
Url (storybook, ...)
...

## Mention

2023-12-13 22:25 UTC, creativeyann17 requested changes
:cookie:

2023-12-13 22:25 UTC, creativeyann17 commented on src/graphql/prescriptions/queries.tsx
> +        coding{
Revert that change (also it had side-effects making prescription.code string -> array making `src/views/Prescriptions/Detail/AnalysisCard/index.tsx:48` silently fails, once revert will be fine)

Easy change to retreive the data you want is in that file but different place:

**ANALYSIS_PATIENT_FRAGMENT**

Update the **requests** part as bellow;

```
 requests: ServiceRequestList(_reference: patient, based_on: "${requestId}") {
      id
      authoredOn
      code @flatten {
        coding{
          code
          system
        }
      }
...
```

2023-12-13 22:25 UTC, creativeyann17 commented on src/views/Prescriptions/Detail/ClinicalInformationCard/index.tsx
> +  const [resquestList, setRequestList] = useState<ServiceRequestEntity[]>([]);
can be revert, your data is now available in `prescription?.subject?.resource?.requests[].coding[]`

2023-12-13 22:25 UTC, creativeyann17 commented on src/api/fhir/index.ts
> +export const fetchServiceRequestEntity = (id: string) =>
No need for a new request, see bellow

2023-12-13 22:25 UTC, creativeyann17 commented on src/views/Prescriptions/Detail/ParentCard/index.tsx
> +    const subjectRequest = extension?.extension?.[1].valueReference?.resource.requests;
same here no new query needed and the data should be available in `prescription?.subject?.resource?.requests[].coding[];`

2023-12-14 17:47 UTC, creativeyann17 approved these changes

2023-12-14 17:51 UTC, atoulous commented on src/views/Prescriptions/Detail/RequestTable.tsx
> +      return sequencingCode?.code;
`sequencingCode?.code || TABLE_EMPTY_PLACE_HOLDER`
vous faites pas ca en général ?

2023-12-14 17:51 UTC, atoulous commented on src/views/Prescriptions/Detail/ClinicalInformationCard/index.tsx
> +            data={prescription.subject?.resource?.requests}
pourquoi avoir retirer le `?` 
ca sécurise

2023-12-14 17:51 UTC, atoulous commented on src/graphql/prescriptions/queries.tsx
> +      code @flatten { coding{ code system } }
`coding {`
il y a des extensions d'IDE pour graphql qui permettent le lintage

2023-12-14 18:40 UTC, claudia1296 commented on src/graphql/prescriptions/queries.tsx
> +      code @flatten { coding{ code system } }
:+1:

2023-12-14 18:41 UTC, claudia1296 commented on src/views/Prescriptions/Detail/RequestTable.tsx
> +      return sequencingCode?.code;
bon point j'avais oublier cette partie

2023-12-14 18:52 UTC, atoulous commented on src/views/Prescriptions/Detail/ClinicalInformationCard/index.tsx
> +            data={prescription.subject?.resource?.requests}
ah exact

2023-12-14 18:52 UTC, atoulous approved these changes

2024-01-11 21:21 UTC, merged